const { spawnSync } = require('node:child_process');
const { writeFileSync } = require('node:fs');
const path = require('node:path');

const projectRef =
  process.env.SUPABASE_PROJECT_ID ||
  process.env.SUPABASE_PROJECT_REF ||
  extractProjectRefFromUrl(process.env.NEXT_PUBLIC_SUPABASE_URL);

if (!projectRef) {
  console.error(
    'Missing project reference. Set SUPABASE_PROJECT_ID (ref) or provide NEXT_PUBLIC_SUPABASE_URL so it can be derived.'
  );
  process.exit(1);
}

const accessToken = process.env.SUPABASE_ACCESS_TOKEN;
const npxCmd = process.platform === 'win32' ? 'npx.cmd' : 'npx';

const args = [
  'supabase@latest',
  'gen',
  'types',
  'typescript',
  '--project-id',
  projectRef,
  '--schema',
  'public',
];

if (accessToken) {
  args.push('--access-token', accessToken);
}

const result = spawnSync(npxCmd, args, {
  env: process.env,
  encoding: 'utf-8',
  stdio: ['inherit', 'pipe', 'inherit'],
  shell: process.platform === 'win32',
});

if (result.error) {
  console.error('Failed to run Supabase CLI:', result.error.message);
  process.exit(1);
}

if (result.status !== 0) {
  console.error('Supabase CLI exited with status', result.status);
  process.exit(result.status || 1);
}

if (!result.stdout) {
  console.error('Supabase CLI did not return any output.');
  process.exit(1);
}

const targetPath = path.resolve(__dirname, '../lib/supabase/database.types.ts');
const banner = [
  '// -----------------------------------------------------------------------------',
  '// This file is auto-generated by `npm run supabase:types`. Do not edit manually.',
  '// -----------------------------------------------------------------------------',
  '',
].join('\n');

writeFileSync(targetPath, `${banner}${result.stdout}`, 'utf-8');
console.log(`Supabase types written to ${targetPath}`);

function extractProjectRefFromUrl(url) {
  if (!url) return null;
  const match = url.match(/^https?:\/\/([a-z0-9-]+)\.supabase\.co/i);
  return match ? match[1] : null;
}
