// This file is auto-generated by the Supabase CLI via npm run supabase:types
// It is safe to commit, and will be replaced whenever you re-run the generator.
// Temporarily using 'any' types until database types can be properly generated

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: Record<string, any>;
    Views: Record<string, any>;
    Functions: Record<string, any>;
    Enums: Record<string, any>;
    CompositeTypes: Record<string, any>;
  };
};
